### ISSUE TITLE
Keep all components in their own file

### ISSUE THREAD

**Issue by zannain** [sidrikblal/jammming#4]
I'm guessing [`A`](https://github.com/sidrikblal/jammming/blob/master/src/components/App/App.js#L12-L26) component may be part of your feature request but as good practice abstract this class out to its own class file. Remember that you can only use `export default` once in a file. So later if you want to import `App` somewhere else, and there is another component in that same file then the second component will inadvertently be imported as well.

**Comment by sidrikblal** [comment]
Thx for making this note.
I added this A component as a last minute joke/eater egg. Its only purpose was to add a className to <body> (on click of the h1 Jammming title) to change the app's background to a gif featuring my favorite Simposon's character. I removed the A component and corresponding css since then and the app is now joke/easter egg free!
